name: Minesweeper
on:
  push:
    branches:
      - main
      - developer
      - add-actions

  pull_request:
    branches:
      - main
      - developer
      - add-actions

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Run tests
        run: sbt clean coverage test

      - name: Coverage Report
        run: sbt coverageReport

        uses: actions/checkout@v2

      - name: Coveralls GitHub Action
        uses: coverallsapp/github-action@v2.0.0

