name: Minesweeper
on:
  push:
    branches:
      - main
      - developer

  pull_request:
    branches:
      - main
      - developer

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Run tests
        run: sbt clean coverage test

      - name: Coverage Report
        run: sbt coverageReport

      - name: Check out code
        uses: actions/checkout@v2

